// shared/sectors.js
// Ticker-to-GICS-sector mapping consumed by both server and client.
// Pattern mirrors shared/benchmarks.js — Object.freeze() constants
// and pure lookup functions with no side-effects.

const GICS_SECTORS = Object.freeze({
  TECHNOLOGY: 'Technology',
  FINANCIALS: 'Financials',
  HEALTHCARE: 'Healthcare',
  CONSUMER_CYCLICAL: 'Consumer Cyclical',
  COMMUNICATION: 'Communication Services',
  INDUSTRIALS: 'Industrials',
  ENERGY: 'Energy',
  UTILITIES: 'Utilities',
  REAL_ESTATE: 'Real Estate',
  MATERIALS: 'Materials',
  CONSUMER_DEFENSIVE: 'Consumer Defensive',
});

const SECTOR_COLORS = Object.freeze({
  [GICS_SECTORS.TECHNOLOGY]: '#6366f1',
  [GICS_SECTORS.FINANCIALS]: '#10b981',
  [GICS_SECTORS.HEALTHCARE]: '#ec4899',
  [GICS_SECTORS.CONSUMER_CYCLICAL]: '#f59e0b',
  [GICS_SECTORS.COMMUNICATION]: '#3b82f6',
  [GICS_SECTORS.INDUSTRIALS]: '#14b8a6',
  [GICS_SECTORS.ENERGY]: '#f97316',
  [GICS_SECTORS.UTILITIES]: '#8b5cf6',
  [GICS_SECTORS.REAL_ESTATE]: '#e11d48',
  [GICS_SECTORS.MATERIALS]: '#06b6d4',
  [GICS_SECTORS.CONSUMER_DEFENSIVE]: '#84cc16',
  OTHER: '#8b8679',
});

// ~120 common tickers covering major US equities, ETFs, and international ADRs.
// Sectors follow GICS classification.
const TICKER_SECTOR_MAP = Object.freeze({
  // Technology
  AAPL: GICS_SECTORS.TECHNOLOGY,
  MSFT: GICS_SECTORS.TECHNOLOGY,
  GOOGL: GICS_SECTORS.COMMUNICATION,
  GOOG: GICS_SECTORS.COMMUNICATION,
  AMZN: GICS_SECTORS.CONSUMER_CYCLICAL,
  NVDA: GICS_SECTORS.TECHNOLOGY,
  META: GICS_SECTORS.COMMUNICATION,
  TSLA: GICS_SECTORS.CONSUMER_CYCLICAL,
  AVGO: GICS_SECTORS.TECHNOLOGY,
  AMD: GICS_SECTORS.TECHNOLOGY,
  INTC: GICS_SECTORS.TECHNOLOGY,
  QCOM: GICS_SECTORS.TECHNOLOGY,
  TXN: GICS_SECTORS.TECHNOLOGY,
  ADBE: GICS_SECTORS.TECHNOLOGY,
  CRM: GICS_SECTORS.TECHNOLOGY,
  ORCL: GICS_SECTORS.TECHNOLOGY,
  CSCO: GICS_SECTORS.TECHNOLOGY,
  IBM: GICS_SECTORS.TECHNOLOGY,
  AMAT: GICS_SECTORS.TECHNOLOGY,
  LRCX: GICS_SECTORS.TECHNOLOGY,
  MU: GICS_SECTORS.TECHNOLOGY,
  NOW: GICS_SECTORS.TECHNOLOGY,
  INTU: GICS_SECTORS.TECHNOLOGY,
  PLTR: GICS_SECTORS.TECHNOLOGY,
  SNOW: GICS_SECTORS.TECHNOLOGY,
  NET: GICS_SECTORS.TECHNOLOGY,
  DDOG: GICS_SECTORS.TECHNOLOGY,
  CRWD: GICS_SECTORS.TECHNOLOGY,
  SNPS: GICS_SECTORS.TECHNOLOGY,
  CDNS: GICS_SECTORS.TECHNOLOGY,
  KLAC: GICS_SECTORS.TECHNOLOGY,
  ASML: GICS_SECTORS.TECHNOLOGY,
  TSM: GICS_SECTORS.TECHNOLOGY,
  SHOP: GICS_SECTORS.TECHNOLOGY,
  SQ: GICS_SECTORS.TECHNOLOGY,
  UBER: GICS_SECTORS.TECHNOLOGY,
  // Financials
  JPM: GICS_SECTORS.FINANCIALS,
  BAC: GICS_SECTORS.FINANCIALS,
  WFC: GICS_SECTORS.FINANCIALS,
  GS: GICS_SECTORS.FINANCIALS,
  MS: GICS_SECTORS.FINANCIALS,
  C: GICS_SECTORS.FINANCIALS,
  V: GICS_SECTORS.FINANCIALS,
  MA: GICS_SECTORS.FINANCIALS,
  AXP: GICS_SECTORS.FINANCIALS,
  BLK: GICS_SECTORS.FINANCIALS,
  SCHW: GICS_SECTORS.FINANCIALS,
  BRK_B: GICS_SECTORS.FINANCIALS,
  BRKB: GICS_SECTORS.FINANCIALS,
  // Healthcare
  JNJ: GICS_SECTORS.HEALTHCARE,
  UNH: GICS_SECTORS.HEALTHCARE,
  PFE: GICS_SECTORS.HEALTHCARE,
  MRK: GICS_SECTORS.HEALTHCARE,
  ABBV: GICS_SECTORS.HEALTHCARE,
  LLY: GICS_SECTORS.HEALTHCARE,
  TMO: GICS_SECTORS.HEALTHCARE,
  ABT: GICS_SECTORS.HEALTHCARE,
  DHR: GICS_SECTORS.HEALTHCARE,
  BMY: GICS_SECTORS.HEALTHCARE,
  AMGN: GICS_SECTORS.HEALTHCARE,
  ISRG: GICS_SECTORS.HEALTHCARE,
  VRTX: GICS_SECTORS.HEALTHCARE,
  MRNA: GICS_SECTORS.HEALTHCARE,
  // Consumer Cyclical
  HD: GICS_SECTORS.CONSUMER_CYCLICAL,
  MCD: GICS_SECTORS.CONSUMER_CYCLICAL,
  NKE: GICS_SECTORS.CONSUMER_CYCLICAL,
  SBUX: GICS_SECTORS.CONSUMER_CYCLICAL,
  DIS: GICS_SECTORS.COMMUNICATION,
  LOW: GICS_SECTORS.CONSUMER_CYCLICAL,
  BKNG: GICS_SECTORS.CONSUMER_CYCLICAL,
  MAR: GICS_SECTORS.CONSUMER_CYCLICAL,
  RCL: GICS_SECTORS.CONSUMER_CYCLICAL,
  CMG: GICS_SECTORS.CONSUMER_CYCLICAL,
  ABNB: GICS_SECTORS.CONSUMER_CYCLICAL,
  // Communication Services
  NFLX: GICS_SECTORS.COMMUNICATION,
  TMUS: GICS_SECTORS.COMMUNICATION,
  VZ: GICS_SECTORS.COMMUNICATION,
  T: GICS_SECTORS.COMMUNICATION,
  CHTR: GICS_SECTORS.COMMUNICATION,
  SPOT: GICS_SECTORS.COMMUNICATION,
  // Industrials
  CAT: GICS_SECTORS.INDUSTRIALS,
  BA: GICS_SECTORS.INDUSTRIALS,
  GE: GICS_SECTORS.INDUSTRIALS,
  HON: GICS_SECTORS.INDUSTRIALS,
  UNP: GICS_SECTORS.INDUSTRIALS,
  LMT: GICS_SECTORS.INDUSTRIALS,
  RTX: GICS_SECTORS.INDUSTRIALS,
  DE: GICS_SECTORS.INDUSTRIALS,
  EMR: GICS_SECTORS.INDUSTRIALS,
  UPS: GICS_SECTORS.INDUSTRIALS,
  FDX: GICS_SECTORS.INDUSTRIALS,
  // Energy
  XOM: GICS_SECTORS.ENERGY,
  CVX: GICS_SECTORS.ENERGY,
  COP: GICS_SECTORS.ENERGY,
  SLB: GICS_SECTORS.ENERGY,
  EOG: GICS_SECTORS.ENERGY,
  OXY: GICS_SECTORS.ENERGY,
  // Utilities
  NEE: GICS_SECTORS.UTILITIES,
  DUK: GICS_SECTORS.UTILITIES,
  SO: GICS_SECTORS.UTILITIES,
  D: GICS_SECTORS.UTILITIES,
  AEP: GICS_SECTORS.UTILITIES,
  // Real Estate
  PLD: GICS_SECTORS.REAL_ESTATE,
  AMT: GICS_SECTORS.REAL_ESTATE,
  CCI: GICS_SECTORS.REAL_ESTATE,
  O: GICS_SECTORS.REAL_ESTATE,
  SPG: GICS_SECTORS.REAL_ESTATE,
  // Materials
  LIN: GICS_SECTORS.MATERIALS,
  SHW: GICS_SECTORS.MATERIALS,
  FCX: GICS_SECTORS.MATERIALS,
  NEM: GICS_SECTORS.MATERIALS,
  // Consumer Defensive
  PG: GICS_SECTORS.CONSUMER_DEFENSIVE,
  KO: GICS_SECTORS.CONSUMER_DEFENSIVE,
  PEP: GICS_SECTORS.CONSUMER_DEFENSIVE,
  WMT: GICS_SECTORS.CONSUMER_DEFENSIVE,
  COST: GICS_SECTORS.CONSUMER_DEFENSIVE,
  PM: GICS_SECTORS.CONSUMER_DEFENSIVE,
  CL: GICS_SECTORS.CONSUMER_DEFENSIVE,
  // ETFs
  SPY: 'ETF',
  QQQ: 'ETF',
  IWM: 'ETF',
  DIA: 'ETF',
  VTI: 'ETF',
  VOO: 'ETF',
  ARKK: 'ETF',
  SMH: 'ETF',
  SOXX: 'ETF',
  XLF: 'ETF',
  XLK: 'ETF',
});

export function normalizeTicker(value) {
  if (typeof value !== 'string') {
    return '';
  }
  const trimmed = value.trim().toUpperCase();
  return trimmed.length > 0 ? trimmed : '';
}

export function resolveSector(ticker, fallback = 'Other') {
  const normalized = normalizeTicker(ticker);
  if (!normalized) {
    return fallback;
  }
  return TICKER_SECTOR_MAP[normalized] ?? fallback;
}

export function getSectorColor(sector) {
  return SECTOR_COLORS[sector] ?? SECTOR_COLORS.OTHER;
}

export function mapHoldingsToSectors(holdings, prices) {
  const sectors = new Map();

  for (const holding of Array.isArray(holdings) ? holdings : []) {
    const ticker = normalizeTicker(holding?.ticker);
    if (!ticker) continue;

    const shares = Number(holding?.shares ?? 0);
    const price = Number(prices?.[ticker] ?? 0);
    if (!Number.isFinite(shares) || !Number.isFinite(price) || price <= 0) continue;

    const value = shares * price;
    if (value <= 0) continue;

    const sector = resolveSector(ticker);
    const entry = sectors.get(sector) ?? { sector, value: 0, tickers: [] };
    entry.value += value;
    // Keep unique tickers for tooltip detail
    if (!entry.tickers.includes(ticker)) {
      entry.tickers.push(ticker);
    }
    sectors.set(sector, entry);
  }

  return Array.from(sectors.values()).sort((a, b) => b.value - a.value);
}

export function getSectorPalette() {
  return { ...SECTOR_COLORS };
}

export { GICS_SECTORS };
export const DEFAULT_FALLBACK_SECTOR = 'Other';
export const ETFS_SECTOR_LABEL = 'ETF';
